#!/bin/zsh

ROOT="$HOME/.config"
PROF="$HOME/.zshrc"

# REMOVE EXISTING CONFIGURATION
if [ -d "$ROOT" ] 
then
	rm -r $ROOT
fi

if [ -d "$PROF" ]
then
        rm $PROF
fi

# INITIALIZE CONFIG FOLDER
mkdir $ROOT
cp -R Prompt $ROOT/Prompt
cp .zshrc $HOME/.zshrc
export PROFILE="$HOME/.zshrc"
. $PROFILE
